# Default values for artifactory.
# This is a YAML-formatted file.

# Beware when changing values here. You should know what you are doing!
# Access the values with {{ .Values.key.subkey }}

# Common
replicaCount: 1
imagePullPolicy: IfNotPresent
initContainerImage: "busybox:1.26.2"
dbEnv:
  dbType: postgresql
  dbName: artifactory
  dbUser: artifactory
  dbPass: artXifactory1973

# DB
dbName: postgresql
dbImage:
  repository: docker.bintray.io/postgres
  version: 9.5.2
dbService:
  name: postgresql
  type: ClusterIP
  externalPort: 5432
  internalPort: 5432
dbPersistence:
  mountPath: "/var/lib/postgresql/data"
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi

# Artifactory
artName: artifactory
artReplicaCount: 1
artImage:
  ## Uncomment following line if you want to run Artifactory-Pro
  #repository: "docker.bintray.io/jfrog/artifactory-oss"
  repository: "docker.bintray.io/jfrog/artifactory-pro"
  version: 5.3.2
artService:
  name: artifactory
  ## For minikube, set this to NodePort, elsewhere use LoadBalancer
  type: ClusterIP
  # For Artifactory-oss use port 80
  externalPort: 8081
  internalPort: 8081
artPersistence:
  mountPath: "/var/opt/jfrog/artifactory"
  enabled: true
  accessMode: ReadWriteOnce
  size: 20Gi

# For Artifactory-oss comment following nginx configuration.
nxName: nginx
nxReplicaCount: 1
nxImage:
  repository: docker.bintray.io/jfrog/nginx-artifactory-pro
  version: 5.3.2
nxService:
  name: nginx
  ## For minikube, set this to NodePort, elsewhere use LoadBalancer
  type: LoadBalancer
  externalPortHttp: 80
  internalPortHttp: 80
  externalPortHttps: 443
  internalPortHttps: 443
nxEnv:
  artUrl: "http://artifactory:8081/artifactory"
  ssl: true
nxPersistence:
  mountPath: "/var/opt/jfrog/nginx"
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
