apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.art_name }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.art_name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.art_service.type }}
  ports:
  - port: {{ .Values.art_service.externalPort }}
    targetPort: {{ .Values.art_service.internalPort }}
    protocol: TCP
    name: {{ .Values.art_service.name }}
  selector:
    app: {{ template "name" . }}
    component: "{{ .Values.art_name }}"