apiVersion: v1
kind: Service
metadata:
  name: {{ template "artifactory.name" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.art_name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.artService.type }}
  ports:
  - port: {{ .Values.artService.externalPort }}
    targetPort: {{ .Values.artService.internalPort }}
    protocol: TCP
    name: {{ .Release.Name }}
  selector:
    app: {{ template "name" . }}
    component: "{{ .Values.artName }}"
    release: {{ .Release.Name }}