apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "artifactory.fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.art_name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.artReplicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        component: "{{ .Values.artName }}"
        release: {{ .Release.Name }}
      annotations:
        pod.beta.kubernetes.io/init-containers: '[{
          "name": "remove-lost-found",
          "image": {{ .Values.initContainerImage | quote }},
          "command": ["rm", "-rf", "{{ .Values.artPersistence.mountPath }}/lost+found"],
          "volumeMounts": [{
              "name": "artifactory-volume",
              "mountPath": {{ .Values.artPersistence.mountPath | quote }}
            }],
          "imagePullPolicy": {{ .Values.imagePullPolicy | quote }}
        }]'
    spec:
      containers:
      - name: {{ .Values.artName }}
        image: "{{ .Values.artImage.repository }}:{{ .Values.artImage.version }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: DB_TYPE
          value: {{ .Values.dbEnv.dbType }}
        - name: DB_USER
          value: {{ .Values.dbEnv.dbName }}
        - name: DB_PASSWORD
          value: {{ .Values.dbEnv.dbPass }}
        - name: DB_HOST
          value: {{ template "database.name" . }}
        ports:
        - containerPort: {{ .Values.artService.internalPort }}
        volumeMounts:
        - mountPath: {{ .Values.artPersistence.mountPath | quote }}
          name: artifactory-volume
      volumes:
      - name: artifactory-volume
      {{- if .Values.artPersistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "artifactory.fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end -}}