apiVersion: v1
kind: Service
metadata:
  name: {{ template "nginxName" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.nxName }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.nxService.type }}
  ports:
  - port: {{ .Values.nxService.externalPortHttp }}
    targetPort: {{ .Values.nxService.internalPortHttp }}
    protocol: TCP
    name: {{ .Values.nxService.name }}http
  - port: {{ .Values.nxService.externalPortHttps }}
    targetPort: {{ .Values.nxService.internalPortHttps }}
    protocol: TCP
    name: {{ .Values.nxService.name }}https
  selector:
    app: {{ template "name" . }}
    component: "{{ .Values.nxName }}"