apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "nginxName" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.nxName }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.nxReplicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        component: "{{ .Values.nxName }}"
        release: {{ .Release.Name }}
      annotations:
        pod.beta.kubernetes.io/init-containers: '[{
          "name": "remove-lost-found",
          "image": {{ .Values.initContainerImage | quote }},
          "command": ["rm", "-rf", "{{ .Values.nxPersistence.mountPath }}/lost+found"],
          "volumeMounts": [{
              "name": "nginx-volume",
              "mountPath": {{ .Values.nxPersistence.mountPath | quote }}
            }],
          "imagePullPolicy": {{ .Values.imagePullPolicy | quote }}
        }]'
    spec:
      containers:
      - name: {{ .Values.nxName }}
        image: "{{ .Values.nxImage.repository }}:{{ .Values.nxImage.version }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: ART_BASE_URL
          value: {{ .Values.nxEnv.artUrl }}
        - name: SSL
          value: "{{ .Values.nxEnv.ssl }}"
        ports:
        - containerPort: {{ .Values.nxService.internalPortHttp }}
        - containerPort: {{ .Values.nxService.internalPortHttps }}
        volumeMounts:
        - mountPath: {{ .Values.nxPersistence.mountPath | quote }}
          name: nginx-volume
      volumes:
      - name: nginx-volume
      {{- if .Values.nxPersistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.nxName }}
      {{- else }}
        emptyDir: {}
      {{- end -}}