apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nx_name }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.nx_name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.nx_service.type }}
  ports:
  - port: {{ .Values.nx_service.externalPortHttp }}
    targetPort: {{ .Values.nx_service.internalPortHttp }}
    protocol: TCP
    name: {{ .Values.nx_service.name }}http
  - port: {{ .Values.nx_service.externalPortHttps }}
    targetPort: {{ .Values.nx_service.internalPortHttps }}
    protocol: TCP
    name: {{ .Values.nx_service.name }}https
  selector:
    app: {{ template "name" . }}
    component: "{{ .Values.nx_name }}"