{{- if .Values.dbPersistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "databaseName" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
  {{- if .Values.dbPersistence.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.dbPersistence.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  accessModes:
    - {{ .Values.dbPersistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.dbPersistence.size | quote }}
{{- end }}
