apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.dbName }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.dbName }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        component: "{{ .Values.dbName }}"
        release: {{ .Release.Name }}
      annotations:
        pod.beta.kubernetes.io/init-containers: '[{
          "name": "remove-lost-found",
          "image": {{ .Values.initContainerImage | quote }},
          "command": ["rm", "-rf", "{{ .Values.dbPersistence.mountPath }}/lost+found"],
          "volumeMounts": [{
              "name": "postgresql-volume",
              "mountPath": {{ .Values.dbPersistence.mountPath | quote }}
            }],
          "imagePullPolicy": {{ .Values.imagePullPolicy | quote }}
        }]'
    spec:
      containers:
      - name: {{ .Values.dbName }}
        image: "{{ .Values.dbImage.repository }}:{{ .Values.dbImage.version }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: POSTGRES_DB
          value: {{ .Values.dbEnv.dbName }}
        - name: POSTGRES_USER
          value: {{ .Values.dbEnv.dbUser }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.dbEnv.dbPass }}
        ports:
        - containerPort: {{ .Values.dbService.internalPort }}
        volumeMounts:
        - mountPath: {{ .Values.dbPersistence.mountPath | quote }}
          name: postgresql-volume
      volumes:
      - name: postgresql-volume
      {{- if .Values.dbPersistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.dbName }}
      {{- else }}
        emptyDir: {}
      {{- end -}}