apiVersion: v1
kind: Service
metadata:
  name: {{ template "database.name" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.dbName }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.dbService.type }}
  ports:
  - port: {{ .Values.dbService.externalPort }}
    targetPort: {{ .Values.dbService.internalPort }}
    protocol: TCP
    name: {{ .Release.Name }}
  selector:
    app: {{ template "name" . }}
    component: "{{ .Values.dbName }}"